name: Scheduled dbt Job

on:
  schedule:
    - cron: "0 * * * *" # 7:55 AM UTC
  workflow_dispatch:  # Add this to allow manual triggering

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.6

      - name: Install dbt-core
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Decode GCP service account key
        run: |
          echo "${{ secrets.GCP_KEY }}" | base64 --decode > ${{ runner.temp }}/key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/key.json

      - name: Install dbt dependencies
        working-directory: ./analytics_test
        run: dbt deps

      - name: Run dbt models
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/key.json
        working-directory: ./analytics_test
        run: dbt build --profiles-dir .
      
  notify_failure:
    runs-on: ubuntu-latest
    needs: run-dbt
    if: failure()
    steps:
      - name: Send Slack failure message
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Error en dbt Prod Job! Revisa los logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_success:
    runs-on: ubuntu-latest
    needs: run-dbt
    if: success()
    steps:
      - name: Send Slack success message
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"dbt Prod Job Exitoso! Revisa los logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
